### ISSUE TITLE
Phantom Frets

### ISSUE THREAD

**Issue by kmcgillivray** [raleighgreen/fretArt#11]
I see the issue, @raleighgreen. if the line drawing pattern connects to a nonexistent fret off of the fretboard, how do we calculate that line?

A few initial ideas...
1. Change the pattern to always connect to a real fret. Would certainly change the end result, but it is an option!
2. Generate however many fake frets you need when the frets are generated, and create a new conditional that determines which frets are real, and should therefore be displayed, and which frets are fake, and should therefore not be displayed. This will include the additional challenge of making sure the line stops drawing at the edge of the fretboard rather than continuing off the fretboard.
3. Use the variables we have for how the frets and strings are spaced to calculate the angle of the line and where it intersects with the edge of the fretboard. This would require some geometry!

Definitely a challenging and interesting problem. I would focus on a couple of the smaller pieces of the problem first, such as simply writing a function that can draw a line between any two frets, while you ruminate on this tougher challenge.

**Comment by raleighgreen** [comment]
Hey, @kmcgillivray - just saw this. Thanks for your thoughts on it!

For what it's worth, unfortunately I can't really go with the 1st option (I sure wish I could, that sure would be easier!). The design should imply that the pattern overflows infinitely off of the fretboard in both directions, and connecting to frets only would work against that illusion.

The 2nd option was kind of the direction I was initially thinking. The fake frets sound pretty doable, but it seems chopping the line at the edge of the fretboard may be kind of tricky. 

The 3rd option sounds really interesting and also potentially complicated, lol!
I'll continue thinking about all of this, but in the meantime, I will definitely take your advice and just try to connect two dots first.

Thanks Kevin!
